
cacti_config = []

cacti_config.append( '-size (bytes) {0}'                                                                                    )
cacti_config.append( '-block size (bytes) {1}'                                                                              )
cacti_config.append( '-associativity 1'                                                                                     )
cacti_config.append( '-read-write port {2}'                                                                                 )
cacti_config.append( '-exclusive read port {3}'                                                                             )
cacti_config.append( '-exclusive write port {4}'                                                                            )
cacti_config.append( '-single ended read ports 0'                                                                           )
cacti_config.append( '-UCA bank count 1'                                                                                    )
cacti_config.append( '-technology (u) {5}'                                                                                  )
cacti_config.append( '-page size (bits) 8192 '                                                                              )
cacti_config.append( '-burst length 8'                                                                                      )
cacti_config.append( '-internal prefetch width 8'                                                                           )
cacti_config.append( '-Data array cell type - "comm-dram"'                                                                  )
cacti_config.append( '-Data array peripheral type - "itrs-hp"'                                                              )
cacti_config.append( '-Tag array cell type - "itrs-hp"'                                                                     )
cacti_config.append( '-Tag array peripheral type - "itrs-hp"'                                                               )
cacti_config.append( '-output/input bus width {6}'                                                                          )
cacti_config.append( '-operating temperature (K) 300'                                                                       )
cacti_config.append( '-cache type "ram"'                                                                                    )
cacti_config.append( '-tag size (b) "default"'                                                                              )
cacti_config.append( '-access mode (normal, sequential, fast) - "normal"'                                                   )
cacti_config.append( '-design objective (weight delay, dynamic power, leakage power, cycle time, area) 0:0:0:0:100'         )
cacti_config.append( '-deviate (delay, dynamic power, leakage power, cycle time, area) 60:100000:100000:100000:1000000'     )
cacti_config.append( '-NUCAdesign objective (weight delay, dynamic power, leakage power, cycle time, area) 100:100:0:0:100' )
cacti_config.append( '-NUCAdeviate (delay, dynamic power, leakage power, cycle time, area) 10:10000:10000:10000:10000'      )
cacti_config.append( '-Optimize ED or ED^2 (ED, ED^2, NONE): "NONE"'                                                        )
cacti_config.append( '-Cache model (NUCA, UCA)  - "UCA"'                                                                    )
cacti_config.append( '-NUCA bank count 0'                                                                                   )
cacti_config.append( '-Wire signalling (fullswing, lowswing, default) - "default"'                                          )
cacti_config.append( '-Wire inside mat - "global"'                                                                          )
cacti_config.append( '-Wire outside mat - "global"'                                                                         )
cacti_config.append( '-Interconnect projection - "conservative"'                                                            )
cacti_config.append( '-Core count 4'                                                                                        )
cacti_config.append( '-Cache level (L2/L3) - "L3"'                                                                          )
cacti_config.append( '-Add ECC - "true"'                                                                                    )
cacti_config.append( '-Print level (DETAILED, CONCISE) - "DETAILED"'                                                        )
cacti_config.append( '-Print input parameters - "true"'                                                                     )
cacti_config.append( '-Force cache config - "false"'                                                                        )
cacti_config.append( '-Ndwl 64'                                                                                             )
cacti_config.append( '-Ndbl 64'                                                                                             )
cacti_config.append( '-Nspd 64'                                                                                             )
cacti_config.append( '-Ndcm 1'                                                                                              )
cacti_config.append( '-Ndsam1 4'                                                                                            )
cacti_config.append( '-Ndsam2 1'                                                                                            )

